package com.sudox.messenger.android.auth

const val FROM_AUTH_PHONE_TO_CODE_ACTION_ID = 0
const val FROM_AUTH_PHONE_TO_COUNTRIES_ACTION_ID = 1
const val FROM_AUTH_CODE_TO_REGISTER_ACTION_ID = 2
const val FROM_AUTH_REGISTER_TO_PEOPLE_FRAGMENT = 3