package ru.sudox.api.auth

const val AUTH_NOT_FOUND_ERROR_CODE = 101
const val AUTH_EXISTS_ERROR_CODE = 102
const val AUTH_DROPPED_ERROR_CODE = 103
const val AUTH_TYPE_INVALID_ERROR_CODE = 104
const val AUTH_CODE_INVALID_ERROR_CODE = 105
const val AUTH_CODE_SENT_ERROR_CODE = 106
const val USER_PHONE_BANNED_ERROR_CODE = 107
const val USER_KEY_HASH_INVALID_ERROR_CODE = 108